name: Conduit API Testing with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Update to Node.js version 16 or higher

      - name: Install Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman collection with Newman
        run: |
          newman run "https://api.getpostman.com/collections/36722846-8fc2f348-1e2b-404a-87fa-b815e7f76275?apikey=${{ secrets.POSTMAN_API_KEY }}" \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export "./newman-report.html"

      - name: Upload Newman HTML report
        uses: actions/upload-artifact@v3
        with:
          name: newman-report-html
          path: ./newman-report.html
