name: Conduit API Testing with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests
        run: |
          postman collection run "36722846-8fc2f348-1e2b-404a-87fa-b815e7f76275" --reporters junit --reporter-junit-export postman-report.xml

      - name: Install CTRF Reporter
        run: npm install -g @ctrf/cli

      - name: Run CTRF Test Reporter
        run: ctrf postman-report.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-results
          path: postman-report.xml
