name: Conduit API Testing with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests and export results
        run: |
          postman collection run "36722846-8fc2f348-1e2b-404a-87fa-b815e7f76275" --reporter-json-export "./postman-results.json"

      - name: Install Newman Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Generate HTML report using Newman Reporter
        run: |
          newman-reporter-htmlextra --collection "./postman-results.json" --reporter-htmlextra-export "./postman-report.html"

      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: postman-report-html
          path: ./postman-report.html
