name: Conduit API Testing with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Install junit-to-ctrf
        run: npm install -g junit-to-ctrf

      - name: Install CTRF Reporter
        run: npm install -g github-actions-ctrf

      - name: Get Postman Collection
        run: |
          curl --location --request GET "https://api.postman.com/collections/36722846-8fc2f348-1e2b-404a-87fa-b815e7f76275" \
          --header "X-Api-Key: ${{ secrets.POSTMAN_API_KEY }}" \
          --output collection.json

      - name: Run API tests
        run: |
          newman run collection.json --reporters junit --reporter-junit-export postman-report.xml
        continue-on-error: true 

      - name: Convert JUnit to CTRF
        run: |
          junit-to-ctrf postman-report.xml --output ctrf-report.json --tool Newman

      - name: Publish AI Test Summary Results
        run: |
          npx github-actions-ctrf ai ctrf-report.json > ai-summary.txt
          echo "====== CTRF AI Test Summary ======"
          cat ai-summary.txt

      - name: Publish Test Summary Results
        run: |
          npx github-actions-ctrf summary ctrf-report.json > summary.txt
          echo "====== CTRF General Test Summary ======"
          cat summary.txt

      - name: Publish Failed Test Summary Results
        run: |
          npx github-actions-ctrf failed ctrf-report.json > failed-summary.txt
          echo "====== CTRF Failed Test Summary ======"
          cat failed-summary.txt

      - name: Publish Detailed Test Summary Results
        run: |
          npx github-actions-ctrf tests ctrf-report.json > detailed-summary.txt
          echo "====== CTRF Detailed Test Summary ======"
          cat detailed-summary.txt
