name: Automated API tests using Postman CLI

on: 
  push:
    branches:
      - main

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      # Step 3: Login to Postman CLI using API key from GitHub Secrets
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # Step 4: Run the Postman collection
      - name: Run API tests
        run: |
          postman collection run "36722846-8fc2f348-1e2b-404a-87fa-b815e7f76275"
