name: Conduit API Testing with Postman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      - name: Run API tests and save output to a file
        run: |
          postman collection run "36722846-8fc2f348-1e2b-404a-87fa-b815e7f76275" --reporters cli --reporter-cli-no-banner > postman-test-results.txt

      - name: Upload Postman test results
        uses: actions/upload-artifact@v3
        with:
          name: postman-test-results
          path: postman-test-results.txt
